-- =============================================================================
-- StencilPro Expert Enterprise
-- Module DB-001: Core System & User Management
-- File: DB001_Core_System.sql
-- PostgreSQL 16 / Supabase Compatible
-- =============================================================================
-- Tables:
--   organizations, organization_settings, schema_migrations, application_config,
--   engineers, roles, permissions, engineer_roles, role_permissions,
--   engineer_sessions, audit_log, activity_log, notifications,
--   notification_preferences, user_preferences, feature_flags
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "unaccent";
CREATE EXTENSION IF NOT EXISTS "btree_gin";

-- ---------------------------------------------------------------------------
-- Shared helper: set updated_at on row modification
-- (Referenced by triggers defined in DB001_Triggers.sql)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_set_updated_at() IS
    'Generic trigger function: sets updated_at = NOW() before any UPDATE.';

-- =============================================================================
-- MODULE 01 — CORE SYSTEM & TENANCY
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: organizations
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS organizations (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    name                VARCHAR(255)    NOT NULL,
    code                VARCHAR(20)     NOT NULL,
    industry_segment    VARCHAR(50)     NOT NULL DEFAULT 'industrial',
    default_ipc_class   VARCHAR(10)     NOT NULL DEFAULT 'class_2',
    default_units       VARCHAR(10)     NOT NULL DEFAULT 'metric',
    default_currency    VARCHAR(3)      NOT NULL DEFAULT 'USD',
    logo_storage_path   TEXT            NULL,
    timezone            VARCHAR(50)     NOT NULL DEFAULT 'UTC',
    address_line1       VARCHAR(255)    NULL,
    address_city        VARCHAR(100)    NULL,
    address_country     VARCHAR(2)      NULL,
    subscription_tier   VARCHAR(50)     NOT NULL DEFAULT 'standard',
    max_engineers       INTEGER         NULL,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted          BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by          UUID            NULL,
    updated_by          UUID            NULL,

    CONSTRAINT pk_organizations
        PRIMARY KEY (id),

    CONSTRAINT uq_organizations_code
        UNIQUE (code),

    CONSTRAINT chk_organizations_industry_segment
        CHECK (industry_segment IN (
            'automotive','medical','consumer','industrial',
            'aerospace','defense','mixed','other'
        )),

    CONSTRAINT chk_organizations_default_ipc_class
        CHECK (default_ipc_class IN ('class_1','class_2','class_3')),

    CONSTRAINT chk_organizations_default_units
        CHECK (default_units IN ('metric','imperial')),

    CONSTRAINT chk_organizations_subscription_tier
        CHECK (subscription_tier IN ('standard','professional','enterprise')),

    CONSTRAINT chk_organizations_max_engineers
        CHECK (max_engineers IS NULL OR max_engineers > 0),

    CONSTRAINT chk_organizations_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        ),

    CONSTRAINT chk_organizations_code_format
        CHECK (code ~ '^[A-Z0-9_\-]{2,20}$')
);

COMMENT ON TABLE organizations IS
    'Top-level tenant entity. Every piece of organizational data in StencilPro '
    'belongs to an organization. Multi-tenancy root. '
    'Soft-deleted on cancellation; retained for 7 years for regulatory compliance.';

COMMENT ON COLUMN organizations.id IS 'UUID primary key. Generated by application before insert.';
COMMENT ON COLUMN organizations.code IS 'Short unique uppercase code used in report headers and file naming (e.g., ACME). Globally unique.';
COMMENT ON COLUMN organizations.default_ipc_class IS 'Organization-level IPC class default. Sets the floor for all projects under this org.';
COMMENT ON COLUMN organizations.subscription_tier IS 'License tier controlling feature access.';
COMMENT ON COLUMN organizations.max_engineers IS 'License seat limit. NULL = unlimited.';
COMMENT ON COLUMN organizations.created_by IS 'UUID of engineer who created this record. NULL for system-created records.';
COMMENT ON COLUMN organizations.updated_by IS 'UUID of engineer who last updated this record.';

-- ---------------------------------------------------------------------------
-- TABLE: organization_settings
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS organization_settings (
    id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id             UUID            NOT NULL,
    setting_key                 VARCHAR(100)    NOT NULL,
    setting_value               TEXT            NULL,
    setting_type                VARCHAR(20)     NOT NULL DEFAULT 'string',
    description                 TEXT            NULL,
    updated_by_engineer_id      UUID            NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  UUID            NULL,
    updated_by                  UUID            NULL,

    CONSTRAINT pk_organization_settings
        PRIMARY KEY (id),

    CONSTRAINT uq_org_settings_org_key
        UNIQUE (organization_id, setting_key),

    CONSTRAINT fk_org_settings_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_org_settings_type
        CHECK (setting_type IN ('string','boolean','integer','json'))
);

COMMENT ON TABLE organization_settings IS
    'Key-value configuration store for per-organization settings. '
    'Supplements the main organizations table for extensible configuration.';

COMMENT ON COLUMN organization_settings.setting_key IS
    'Dot-notation key (e.g., report.header.show_logo, approval.four_eyes_enabled).';
COMMENT ON COLUMN organization_settings.setting_type IS
    'Data type hint for the application to parse setting_value: string, boolean, integer, json.';

-- ---------------------------------------------------------------------------
-- TABLE: schema_migrations
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_migrations (
    version_num     VARCHAR(32)     NOT NULL,
    applied_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_schema_migrations
        PRIMARY KEY (version_num)
);

COMMENT ON TABLE schema_migrations IS
    'Tracks applied Alembic migration revisions. Managed exclusively by the '
    'migration toolchain — never manually modified.';

-- ---------------------------------------------------------------------------
-- TABLE: application_config
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS application_config (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    config_key      VARCHAR(100)    NOT NULL,
    config_value    TEXT            NOT NULL,
    config_type     VARCHAR(20)     NOT NULL DEFAULT 'string',
    environment     VARCHAR(20)     NOT NULL DEFAULT 'all',
    description     TEXT            NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_application_config
        PRIMARY KEY (id),

    CONSTRAINT uq_app_config_key_env
        UNIQUE (config_key, environment),

    CONSTRAINT chk_app_config_type
        CHECK (config_type IN ('string','boolean','integer','json')),

    CONSTRAINT chk_app_config_environment
        CHECK (environment IN ('all','development','production','test'))
);

COMMENT ON TABLE application_config IS
    'System-wide configuration values not scoped to any organization. '
    'Read-only in production; modified only by Super Admin.';

COMMENT ON COLUMN application_config.environment IS
    'Which deployment environment this config applies to. '
    '''all'' applies to every environment.';

-- =============================================================================
-- MODULE 02 — USER MANAGEMENT & SECURITY
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: engineers
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS engineers (
    id                      UUID            NOT NULL,
    organization_id         UUID            NOT NULL,
    email                   VARCHAR(255)    NOT NULL,
    full_name               VARCHAR(255)    NOT NULL,
    title                   VARCHAR(100)    NULL,
    employee_id             VARCHAR(50)     NULL,
    ipc_certifications      TEXT[]          NOT NULL DEFAULT '{}',
    default_ipc_class       VARCHAR(10)     NULL,
    preferred_units         VARCHAR(10)     NOT NULL DEFAULT 'metric',
    signature_storage_path  TEXT            NULL,
    avatar_storage_path     TEXT            NULL,
    phone                   VARCHAR(30)     NULL,
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted              BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMPTZ     NULL,
    last_login_at           TIMESTAMPTZ     NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by              UUID            NULL,
    updated_by              UUID            NULL,

    CONSTRAINT pk_engineers
        PRIMARY KEY (id),

    CONSTRAINT uq_engineers_email
        UNIQUE (email),

    CONSTRAINT fk_engineers_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_engineers_preferred_units
        CHECK (preferred_units IN ('metric','imperial')),

    CONSTRAINT chk_engineers_default_ipc_class
        CHECK (default_ipc_class IS NULL OR
               default_ipc_class IN ('class_1','class_2','class_3')),

    CONSTRAINT chk_engineers_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        ),

    CONSTRAINT chk_engineers_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$')
);

COMMENT ON TABLE engineers IS
    'Human users of the system. id matches Supabase Auth user UUID exactly. '
    'Deleted engineers are soft-deleted; all authored records retain their '
    'engineer attribution for audit trail purposes.';

COMMENT ON COLUMN engineers.id IS
    'UUID primary key — MUST match the Supabase Auth auth.users.id for this engineer.';
COMMENT ON COLUMN engineers.ipc_certifications IS
    'Array of IPC certification codes held by this engineer (e.g., {''IPC-A-610'', ''IPC-7711''}).';
COMMENT ON COLUMN engineers.default_ipc_class IS
    'Personal IPC class default. When set, overrides the organization default for this engineer.';

-- ---------------------------------------------------------------------------
-- TABLE: roles
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roles (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID            NULL,
    name            VARCHAR(100)    NOT NULL,
    code            VARCHAR(50)     NOT NULL,
    description     TEXT            NULL,
    is_system_role  BOOLEAN         NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_roles
        PRIMARY KEY (id),

    CONSTRAINT uq_roles_code_org
        UNIQUE (code, organization_id),

    CONSTRAINT fk_roles_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE roles IS
    'Role definitions. organization_id = NULL means a system role available to all orgs. '
    'System roles (is_system_role = TRUE) cannot be deleted.';

COMMENT ON COLUMN roles.code IS
    'Machine-readable role identifier (e.g., viewer, engineer, senior_engineer, admin, super_admin).';
COMMENT ON COLUMN roles.organization_id IS
    'NULL = system role available to all organizations. '
    'Populated = custom role scoped to that organization.';

-- ---------------------------------------------------------------------------
-- TABLE: permissions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS permissions (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(100)    NOT NULL,
    module          VARCHAR(50)     NOT NULL,
    description     TEXT            NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_permissions
        PRIMARY KEY (id),

    CONSTRAINT uq_permissions_code
        UNIQUE (code)
);

COMMENT ON TABLE permissions IS
    'Atomic permission definitions. Each permission controls one specific system capability. '
    'Permissions are system-defined and cannot be created by engineers.';

COMMENT ON COLUMN permissions.code IS
    'Dot-notation permission identifier (e.g., project.create, stencil.approve, rule_set.edit).';
COMMENT ON COLUMN permissions.module IS
    'Which application module this permission governs (e.g., projects, stencils, rules, admin).';

-- ---------------------------------------------------------------------------
-- TABLE: engineer_roles
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS engineer_roles (
    id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
    engineer_id             UUID            NOT NULL,
    role_id                 UUID            NOT NULL,
    assigned_by_engineer_id UUID            NOT NULL,
    assigned_at             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    expires_at              TIMESTAMPTZ     NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by              UUID            NULL,
    updated_by              UUID            NULL,

    CONSTRAINT pk_engineer_roles
        PRIMARY KEY (id),

    CONSTRAINT uq_engineer_roles_engineer_role
        UNIQUE (engineer_id, role_id),

    CONSTRAINT fk_engineer_roles_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_engineer_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_engineer_roles_assigned_by
        FOREIGN KEY (assigned_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_engineer_roles_expires
        CHECK (expires_at IS NULL OR expires_at > assigned_at)
);

COMMENT ON TABLE engineer_roles IS
    'Junction table: assigns roles to engineers. An engineer may hold multiple roles; '
    'the highest-privilege role applies. expires_at supports temporary role assignments.';

COMMENT ON COLUMN engineer_roles.expires_at IS
    'Optional expiry for temporary role assignments. '
    'Application enforces downgrade at expiry; DB stores the intent.';

-- ---------------------------------------------------------------------------
-- TABLE: role_permissions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS role_permissions (
    id              UUID    NOT NULL DEFAULT gen_random_uuid(),
    role_id         UUID    NOT NULL,
    permission_id   UUID    NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID    NULL,
    updated_by      UUID    NULL,

    CONSTRAINT pk_role_permissions
        PRIMARY KEY (id),

    CONSTRAINT uq_role_permissions_role_permission
        UNIQUE (role_id, permission_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE role_permissions IS
    'Junction table: maps permissions to roles. '
    'Cascade delete on role: removing a role removes all its permission mappings.';

-- ---------------------------------------------------------------------------
-- TABLE: engineer_sessions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS engineer_sessions (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    engineer_id         UUID            NOT NULL,
    session_token_hash  VARCHAR(64)     NOT NULL,
    app_version         VARCHAR(20)     NOT NULL,
    os_platform         VARCHAR(50)     NULL,
    started_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    last_active_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    ended_at            TIMESTAMPTZ     NULL,
    ended_reason        VARCHAR(50)     NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by          UUID            NULL,
    updated_by          UUID            NULL,

    CONSTRAINT pk_engineer_sessions
        PRIMARY KEY (id),

    CONSTRAINT fk_engineer_sessions_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_engineer_sessions_ended_reason
        CHECK (ended_reason IS NULL OR
               ended_reason IN ('logout','timeout','forced','expired')),

    CONSTRAINT chk_engineer_sessions_token_hash_length
        CHECK (LENGTH(session_token_hash) = 64),

    CONSTRAINT chk_engineer_sessions_ended
        CHECK (
            (ended_at IS NULL AND ended_reason IS NULL) OR
            (ended_at IS NOT NULL AND ended_reason IS NOT NULL)
        )
);

COMMENT ON TABLE engineer_sessions IS
    'Tracks desktop application sessions for security monitoring and activity attribution. '
    'session_token_hash is a SHA-256 hash of the session token — never store plaintext tokens.';

COMMENT ON COLUMN engineer_sessions.session_token_hash IS
    'SHA-256 hex hash of the session token. 64 hex characters. Never store plaintext.';

-- =============================================================================
-- MODULE 20 — AUDIT, ACTIVITY & NOTIFICATIONS
-- (Included in DB-001 because audit triggers depend on these tables)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: audit_log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGSERIAL       NOT NULL,
    organization_id UUID            NULL,
    engineer_id     UUID            NULL,
    action          VARCHAR(20)     NOT NULL,
    table_name      VARCHAR(100)    NOT NULL,
    record_id       UUID            NOT NULL,
    old_values      JSONB           NULL,
    new_values      JSONB           NULL,
    changed_fields  TEXT[]          NULL,
    ip_address      INET            NULL,
    session_id      UUID            NULL,
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_audit_log
        PRIMARY KEY (id),

    CONSTRAINT chk_audit_log_action
        CHECK (action IN ('INSERT','UPDATE','DELETE'))
) PARTITION BY RANGE (occurred_at);

COMMENT ON TABLE audit_log IS
    'Append-only immutable audit trail. Partitioned by occurred_at (monthly). '
    'Retained for 7 years minimum (automotive IATF 16949, medical ISO 13485, '
    'aerospace AS9100 regulatory requirement). No UPDATE or DELETE permitted by any role.';

COMMENT ON COLUMN audit_log.id IS 'BIGSERIAL sequence — guarantees strict chronological ordering.';
COMMENT ON COLUMN audit_log.organization_id IS 'NULL for system-level events not tied to an organization.';
COMMENT ON COLUMN audit_log.engineer_id IS 'NULL for system-initiated actions (triggers, background jobs).';
COMMENT ON COLUMN audit_log.old_values IS 'JSONB snapshot of row before UPDATE or DELETE. NULL for INSERT.';
COMMENT ON COLUMN audit_log.new_values IS 'JSONB snapshot of row after INSERT or UPDATE. NULL for DELETE.';
COMMENT ON COLUMN audit_log.changed_fields IS 'Array of column names that changed during UPDATE.';

-- Create initial partition covering current and next year
DO $$
DECLARE
    start_year  INT := EXTRACT(YEAR FROM NOW())::INT;
    start_month INT := EXTRACT(MONTH FROM NOW())::INT;
    part_start  DATE;
    part_end    DATE;
    part_name   TEXT;
    m           INT;
BEGIN
    -- Create 3 months of partitions: prior month, current month, next month
    FOR m IN -1..2 LOOP
        part_start := DATE_TRUNC('month', NOW() + (m || ' months')::INTERVAL)::DATE;
        part_end   := (part_start + INTERVAL '1 month')::DATE;
        part_name  := 'audit_log_' || TO_CHAR(part_start, 'YYYY_MM');

        EXECUTE FORMAT(
            'CREATE TABLE IF NOT EXISTS %I '
            'PARTITION OF audit_log '
            'FOR VALUES FROM (%L) TO (%L)',
            part_name, part_start, part_end
        );
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- TABLE: activity_log
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_log (
    id              BIGSERIAL       NOT NULL,
    organization_id UUID            NOT NULL,
    engineer_id     UUID            NOT NULL,
    activity_type   VARCHAR(100)    NOT NULL,
    entity_type     VARCHAR(50)     NULL,
    entity_id       UUID            NULL,
    metadata        JSONB           NULL,
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_activity_log
        PRIMARY KEY (id)
) PARTITION BY RANGE (occurred_at);

COMMENT ON TABLE activity_log IS
    'User activity tracking for usage analytics and engineer contribution metrics. '
    'Partitioned monthly. Retained for 2 years. '
    'Not audited itself (it is an audit-class table).';

COMMENT ON COLUMN activity_log.activity_type IS
    'Descriptor of the action taken (e.g., login, view_project, run_rule_check, '
    'create_stencil, generate_report, open_investigation).';

-- Create initial activity_log partition
DO $$
DECLARE
    part_start  DATE;
    part_end    DATE;
    part_name   TEXT;
    m           INT;
BEGIN
    FOR m IN -1..2 LOOP
        part_start := DATE_TRUNC('month', NOW() + (m || ' months')::INTERVAL)::DATE;
        part_end   := (part_start + INTERVAL '1 month')::DATE;
        part_name  := 'activity_log_' || TO_CHAR(part_start, 'YYYY_MM');

        EXECUTE FORMAT(
            'CREATE TABLE IF NOT EXISTS %I '
            'PARTITION OF activity_log '
            'FOR VALUES FROM (%L) TO (%L)',
            part_name, part_start, part_end
        );
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- TABLE: notifications
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notifications (
    id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id         UUID            NOT NULL,
    recipient_engineer_id   UUID            NOT NULL,
    notification_type       VARCHAR(50)     NOT NULL,
    title                   VARCHAR(255)    NOT NULL,
    content                 TEXT            NOT NULL,
    entity_type             VARCHAR(50)     NULL,
    entity_id               UUID            NULL,
    is_read                 BOOLEAN         NOT NULL DEFAULT FALSE,
    read_at                 TIMESTAMPTZ     NULL,
    expires_at              TIMESTAMPTZ     NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by              UUID            NULL,
    updated_by              UUID            NULL,

    CONSTRAINT pk_notifications
        PRIMARY KEY (id),

    CONSTRAINT fk_notifications_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_engineer_id)
        REFERENCES engineers (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_notifications_type
        CHECK (notification_type IN (
            'design_approval_requested',
            'design_approved',
            'design_rejected',
            'rule_override_requested',
            'rule_override_approved',
            'rule_override_rejected',
            'defect_investigation_assigned',
            'investigation_closed',
            'knowledge_review_flag',
            'critical_rule_failure',
            'spi_correlation_available',
            'role_changed',
            'project_status_changed'
        )),

    CONSTRAINT chk_notifications_read_state
        CHECK (
            (is_read = FALSE AND read_at IS NULL) OR
            (is_read = TRUE  AND read_at IS NOT NULL)
        )
);

COMMENT ON TABLE notifications IS
    'In-app notifications delivered to individual engineers. '
    'Transient operational data — not audited. Expires_at supports TTL-based cleanup.';

-- ---------------------------------------------------------------------------
-- TABLE: notification_preferences
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notification_preferences (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    engineer_id         UUID            NOT NULL,
    notification_type   VARCHAR(50)     NOT NULL,
    in_app_enabled      BOOLEAN         NOT NULL DEFAULT TRUE,
    email_enabled       BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by          UUID            NULL,
    updated_by          UUID            NULL,

    CONSTRAINT pk_notification_preferences
        PRIMARY KEY (id),

    CONSTRAINT uq_notification_preferences_engineer_type
        UNIQUE (engineer_id, notification_type),

    CONSTRAINT fk_notification_preferences_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_notification_preferences_type
        CHECK (notification_type IN (
            'design_approval_requested',
            'design_approved',
            'design_rejected',
            'rule_override_requested',
            'rule_override_approved',
            'rule_override_rejected',
            'defect_investigation_assigned',
            'investigation_closed',
            'knowledge_review_flag',
            'critical_rule_failure',
            'spi_correlation_available',
            'role_changed',
            'project_status_changed'
        ))
);

COMMENT ON TABLE notification_preferences IS
    'Per-engineer preferences for which notification types to receive '
    'and via which channels (in-app vs email).';

-- =============================================================================
-- MODULE 21 — APPLICATION SETTINGS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: user_preferences
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_preferences (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    engineer_id     UUID            NOT NULL,
    preference_key  VARCHAR(100)    NOT NULL,
    preference_value TEXT           NULL,
    preference_type VARCHAR(20)     NOT NULL DEFAULT 'string',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_user_preferences
        PRIMARY KEY (id),

    CONSTRAINT uq_user_preferences_engineer_key
        UNIQUE (engineer_id, preference_key),

    CONSTRAINT fk_user_preferences_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_user_preferences_type
        CHECK (preference_type IN ('string','boolean','integer','json'))
);

COMMENT ON TABLE user_preferences IS
    'Per-engineer application preferences (theme, units, defaults, display settings). '
    'Not audited — personal UX settings.';

-- ---------------------------------------------------------------------------
-- TABLE: feature_flags
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS feature_flags (
    id                      UUID        NOT NULL DEFAULT gen_random_uuid(),
    flag_key                VARCHAR(100) NOT NULL,
    description             TEXT        NOT NULL,
    is_enabled_globally     BOOLEAN     NOT NULL DEFAULT FALSE,
    enabled_for_org_ids     UUID[]      NOT NULL DEFAULT '{}',
    enabled_for_tiers       TEXT[]      NOT NULL DEFAULT '{}',
    rollout_percentage      INTEGER     NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by              UUID        NULL,
    updated_by              UUID        NULL,

    CONSTRAINT pk_feature_flags
        PRIMARY KEY (id),

    CONSTRAINT uq_feature_flags_key
        UNIQUE (flag_key),

    CONSTRAINT chk_feature_flags_rollout
        CHECK (rollout_percentage IS NULL OR
               (rollout_percentage >= 0 AND rollout_percentage <= 100))
);

COMMENT ON TABLE feature_flags IS
    'Feature toggle system for progressive feature rollout. '
    'Controls which features are visible per organization, subscription tier, '
    'or globally.';

COMMENT ON COLUMN feature_flags.rollout_percentage IS
    '0–100 for gradual percentage-based rollout. NULL = not using percentage rollout.';

COMMIT;
