-- =============================================================================
-- StencilPro Expert Enterprise
-- Module DB-002: Projects & Customers
-- File: DB002_Projects.sql
-- PostgreSQL 16 / Supabase Compatible
-- =============================================================================
-- Tables:
--   customers, customer_contacts, products,
--   projects, project_members, project_revisions,
--   project_notes, project_attachments, project_tags,
--   project_tag_assignments, project_activity, project_templates
-- =============================================================================
-- Prerequisites: DB001_Core_System.sql must be applied first.
-- =============================================================================

BEGIN;

-- =============================================================================
-- MODULE 03 — PROJECTS & CUSTOMERS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: customers
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customers (
    id                              UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id                 UUID            NOT NULL,
    name                            VARCHAR(255)    NOT NULL,
    code                            VARCHAR(20)     NOT NULL,
    industry_segment                VARCHAR(50)     NOT NULL DEFAULT 'industrial',
    required_ipc_class              VARCHAR(10)     NOT NULL DEFAULT 'class_2',
    regulatory_requirements         TEXT[]          NOT NULL DEFAULT '{}',
    requires_signed_reports         BOOLEAN         NOT NULL DEFAULT FALSE,
    approved_paste_ids              UUID[]          NOT NULL DEFAULT '{}',
    approved_stencil_material_ids   UUID[]          NOT NULL DEFAULT '{}',
    special_requirements_notes      TEXT            NULL,
    contact_name                    VARCHAR(255)    NULL,
    contact_email                   VARCHAR(255)    NULL,
    contact_phone                   VARCHAR(30)     NULL,
    website_url                     TEXT            NULL,
    is_active                       BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted                      BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at                      TIMESTAMPTZ     NULL,
    created_at                      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                      UUID            NULL,
    updated_by                      UUID            NULL,

    CONSTRAINT pk_customers
        PRIMARY KEY (id),

    CONSTRAINT uq_customers_org_code
        UNIQUE (organization_id, code),

    CONSTRAINT fk_customers_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_customers_industry_segment
        CHECK (industry_segment IN (
            'automotive','medical','consumer','industrial',
            'aerospace','defense','mixed','other'
        )),

    CONSTRAINT chk_customers_required_ipc_class
        CHECK (required_ipc_class IN ('class_1','class_2','class_3')),

    CONSTRAINT chk_customers_code_format
        CHECK (code ~ '^[A-Z0-9_\-]{1,20}$'),

    CONSTRAINT chk_customers_contact_email_format
        CHECK (
            contact_email IS NULL OR
            contact_email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'
        ),

    CONSTRAINT chk_customers_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        )
);

COMMENT ON TABLE customers IS
    'External customers or internal business units for whom PCB assemblies are manufactured. '
    'Customer requirements (IPC class, approved materials) cascade to all projects '
    'and drive engineering rule activation. Scoped to organization.';

COMMENT ON COLUMN customers.id IS 'UUID primary key. Generated by application before insert.';
COMMENT ON COLUMN customers.organization_id IS 'Owning organization. RLS enforces isolation.';
COMMENT ON COLUMN customers.code IS 'Short uppercase code used in file naming and report headers (e.g., FORD, MEDCO). Unique per organization.';
COMMENT ON COLUMN customers.required_ipc_class IS 'Minimum IPC class this customer requires. Projects under this customer cannot use a lower class. Enforced by application and DB trigger.';
COMMENT ON COLUMN customers.regulatory_requirements IS 'Array of regulatory standards required (e.g., {RoHS, REACH, MIL-STD-2000}). Drives material constraint rules.';
COMMENT ON COLUMN customers.approved_paste_ids IS 'Array of solder_paste UUIDs that this customer has approved. If populated, rule engine flags use of non-listed pastes.';
COMMENT ON COLUMN customers.approved_stencil_material_ids IS 'Array of stencil_material UUIDs approved by this customer.';
COMMENT ON COLUMN customers.requires_signed_reports IS 'When TRUE, generated reports must carry an engineer signature before delivery to customer.';

-- ---------------------------------------------------------------------------
-- TABLE: customer_contacts
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customer_contacts (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    customer_id     UUID            NOT NULL,
    organization_id UUID            NOT NULL,
    full_name       VARCHAR(255)    NOT NULL,
    title           VARCHAR(100)    NULL,
    email           VARCHAR(255)    NULL,
    phone           VARCHAR(30)     NULL,
    department      VARCHAR(100)    NULL,
    is_primary      BOOLEAN         NOT NULL DEFAULT FALSE,
    contact_type    VARCHAR(30)     NOT NULL DEFAULT 'technical',
    notes           TEXT            NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted      BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ     NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_customer_contacts
        PRIMARY KEY (id),

    CONSTRAINT fk_customer_contacts_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_customer_contacts_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_customer_contacts_type
        CHECK (contact_type IN ('technical','commercial','quality','executive','other')),

    CONSTRAINT chk_customer_contacts_email_format
        CHECK (
            email IS NULL OR
            email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'
        ),

    CONSTRAINT chk_customer_contacts_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        )
);

COMMENT ON TABLE customer_contacts IS
    'Individual contacts at a customer organization. A customer may have multiple contacts '
    'across different departments (technical, commercial, quality). '
    'One contact per customer may be flagged is_primary.';

COMMENT ON COLUMN customer_contacts.is_primary IS
    'When TRUE, this is the primary contact for this customer. '
    'Only one contact per customer should be marked primary (enforced by application).';
COMMENT ON COLUMN customer_contacts.contact_type IS
    'Role of this contact: technical (engineering liaison), commercial (purchasing), '
    'quality (QA/QC manager), executive, or other.';

-- ---------------------------------------------------------------------------
-- TABLE: products
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS products (
    id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id             UUID            NOT NULL,
    customer_id                 UUID            NOT NULL,
    name                        VARCHAR(255)    NOT NULL,
    part_number                 VARCHAR(100)    NULL,
    product_family              VARCHAR(100)    NULL,
    market_segment              VARCHAR(50)     NOT NULL DEFAULT 'industrial',
    regulatory_requirements     TEXT[]          NOT NULL DEFAULT '{}',
    description                 TEXT            NULL,
    is_active                   BOOLEAN         NOT NULL DEFAULT TRUE,
    is_deleted                  BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMPTZ     NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  UUID            NULL,
    updated_by                  UUID            NULL,

    CONSTRAINT pk_products
        PRIMARY KEY (id),

    CONSTRAINT fk_products_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_products_market_segment
        CHECK (market_segment IN (
            'consumer','industrial','medical','automotive',
            'aerospace','defense','other'
        )),

    CONSTRAINT chk_products_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        )
);

COMMENT ON TABLE products IS
    'The end-product (commercial device) that contains one or more PCB assemblies. '
    'Connects PCB engineering work to the commercial product context. '
    'A product may span multiple PCB assemblies and project generations.';

COMMENT ON COLUMN products.part_number IS 'Customer-assigned commercial part number for this product.';
COMMENT ON COLUMN products.product_family IS 'Product line or family grouping (e.g., PowerDrive Series, MedSense Platform).';
COMMENT ON COLUMN products.regulatory_requirements IS
    'Regulatory standards required for this product, in addition to customer-level requirements. '
    'Union of customer + product requirements drives material constraint rules.';

-- ---------------------------------------------------------------------------
-- TABLE: projects
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS projects (
    id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id             UUID            NOT NULL,
    customer_id                 UUID            NOT NULL,
    product_id                  UUID            NULL,
    lead_engineer_id            UUID            NOT NULL,
    project_number              VARCHAR(50)     NOT NULL,
    name                        VARCHAR(255)    NOT NULL,
    description                 TEXT            NULL,
    status                      VARCHAR(30)     NOT NULL DEFAULT 'draft',
    phase                       VARCHAR(30)     NOT NULL DEFAULT 'npi',
    ipc_class                   VARCHAR(10)     NOT NULL DEFAULT 'class_2',
    target_yield_pct            NUMERIC(6,3)    NULL,
    start_date                  DATE            NULL,
    target_completion_date      DATE            NULL,
    actual_completion_date      DATE            NULL,
    tags                        TEXT[]          NOT NULL DEFAULT '{}',
    is_deleted                  BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMPTZ     NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  UUID            NULL,
    updated_by                  UUID            NULL,

    CONSTRAINT pk_projects
        PRIMARY KEY (id),

    CONSTRAINT uq_projects_org_number
        UNIQUE (organization_id, project_number),

    CONSTRAINT fk_projects_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_projects_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_projects_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_projects_lead_engineer
        FOREIGN KEY (lead_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_projects_status
        CHECK (status IN (
            'draft','active','on_hold','in_review',
            'approved','completed','archived'
        )),

    CONSTRAINT chk_projects_phase
        CHECK (phase IN (
            'npi','pre_production','production',
            'eco','sustaining','end_of_life'
        )),

    CONSTRAINT chk_projects_ipc_class
        CHECK (ipc_class IN ('class_1','class_2','class_3')),

    CONSTRAINT chk_projects_target_yield
        CHECK (target_yield_pct IS NULL OR
               (target_yield_pct >= 0 AND target_yield_pct <= 100)),

    CONSTRAINT chk_projects_dates
        CHECK (
            target_completion_date IS NULL OR
            start_date IS NULL OR
            target_completion_date >= start_date
        ),

    CONSTRAINT chk_projects_actual_completion
        CHECK (
            actual_completion_date IS NULL OR
            start_date IS NULL OR
            actual_completion_date >= start_date
        ),

    CONSTRAINT chk_projects_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        )
);

COMMENT ON TABLE projects IS
    'Primary organizational container for all stencil engineering work on a specific PCB assembly. '
    'A project owns: PCB assemblies, stencil designs, defect investigations, experiments, '
    'and generated reports. All downstream engineering work traces to a project. '
    'Status transitions are logged as project_notes automatically.';

COMMENT ON COLUMN projects.id IS 'UUID primary key. Generated by application before insert.';
COMMENT ON COLUMN projects.organization_id IS 'Owning organization. RLS enforces isolation.';
COMMENT ON COLUMN projects.project_number IS 'Human-readable sequential identifier. Format configured per org (e.g., ACME-2026-0042). Unique per organization.';
COMMENT ON COLUMN projects.status IS 'Project lifecycle status. Transitions: draft→active→on_hold/in_review/completed→archived. Each transition creates a system project_note.';
COMMENT ON COLUMN projects.phase IS 'Engineering phase: npi (new product introduction), pre_production, production, eco (engineering change order), sustaining, end_of_life.';
COMMENT ON COLUMN projects.ipc_class IS 'IPC workmanship class for this project. Must be equal to or stricter than customer.required_ipc_class. Enforced by trigger.';
COMMENT ON COLUMN projects.target_yield_pct IS 'Target first-pass yield percentage (0–100). Used by Intelligence Engine as yield goal.';
COMMENT ON COLUMN projects.tags IS 'Freeform classification tags for search and filtering (stored denormalized for query convenience; also normalized in project_tags).';

-- ---------------------------------------------------------------------------
-- TABLE: project_members
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_members (
    id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id                  UUID            NOT NULL,
    engineer_id                 UUID            NOT NULL,
    organization_id             UUID            NOT NULL,
    role_on_project             VARCHAR(30)     NOT NULL DEFAULT 'contributor',
    assigned_at                 TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    assigned_by_engineer_id     UUID            NOT NULL,
    removed_at                  TIMESTAMPTZ     NULL,
    removed_by_engineer_id      UUID            NULL,
    removal_reason              TEXT            NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  UUID            NULL,
    updated_by                  UUID            NULL,

    CONSTRAINT pk_project_members
        PRIMARY KEY (id),

    CONSTRAINT uq_project_members_project_engineer
        UNIQUE (project_id, engineer_id),

    CONSTRAINT fk_project_members_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_members_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_members_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_members_assigned_by
        FOREIGN KEY (assigned_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_members_removed_by
        FOREIGN KEY (removed_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_members_role
        CHECK (role_on_project IN (
            'lead','reviewer','contributor','observer'
        )),

    CONSTRAINT chk_project_members_removal
        CHECK (
            (removed_at IS NULL AND removed_by_engineer_id IS NULL) OR
            (removed_at IS NOT NULL AND removed_by_engineer_id IS NOT NULL)
        )
);

COMMENT ON TABLE project_members IS
    'Junction table assigning engineers to projects beyond the lead engineer. '
    'An engineer may have one active assignment per project. '
    'Removal is soft (removed_at timestamp) to preserve history.';

COMMENT ON COLUMN project_members.role_on_project IS
    'Engineering role on this project: lead (primary owner), reviewer (approval authority), '
    'contributor (creates and edits data), observer (read-only access).';
COMMENT ON COLUMN project_members.removed_at IS
    'When set, this assignment is no longer active. '
    'Engineer retains read access per RLS policy but cannot create new records.';

-- ---------------------------------------------------------------------------
-- TABLE: project_revisions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_revisions (
    id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id              UUID            NOT NULL,
    organization_id         UUID            NOT NULL,
    revision_number         INTEGER         NOT NULL,
    revision_code           VARCHAR(10)     NOT NULL,
    revision_type           VARCHAR(30)     NOT NULL DEFAULT 'minor_change',
    change_summary          TEXT            NOT NULL,
    change_reason           VARCHAR(50)     NOT NULL DEFAULT 'engineering_change',
    authored_by_engineer_id UUID            NOT NULL,
    approved_by_engineer_id UUID            NULL,
    approved_at             TIMESTAMPTZ     NULL,
    project_snapshot        JSONB           NOT NULL DEFAULT '{}',
    is_current              BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by              UUID            NULL,
    updated_by              UUID            NULL,

    CONSTRAINT pk_project_revisions
        PRIMARY KEY (id),

    CONSTRAINT uq_project_revisions_project_number
        UNIQUE (project_id, revision_number),

    CONSTRAINT uq_project_revisions_project_code
        UNIQUE (project_id, revision_code),

    CONSTRAINT fk_project_revisions_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_revisions_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_revisions_authored_by
        FOREIGN KEY (authored_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_revisions_approved_by
        FOREIGN KEY (approved_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_revisions_type
        CHECK (revision_type IN (
            'initial_release','minor_change','major_change',
            'emergency_change','eco'
        )),

    CONSTRAINT chk_project_revisions_reason
        CHECK (change_reason IN (
            'engineering_change','customer_request','defect_correction',
            'cost_reduction','regulatory_update','process_improvement','other'
        )),

    CONSTRAINT chk_project_revisions_revision_number
        CHECK (revision_number > 0),

    CONSTRAINT chk_project_revisions_approval
        CHECK (
            (approved_at IS NULL AND approved_by_engineer_id IS NULL) OR
            (approved_at IS NOT NULL AND approved_by_engineer_id IS NOT NULL)
        )
);

COMMENT ON TABLE project_revisions IS
    'Versioned snapshots of a project at each formal revision point. '
    'Provides a complete revision history for regulatory audit (IATF 16949, ISO 13485, AS9100). '
    'project_snapshot is a JSONB copy of key project metadata at time of revision. '
    'Only one revision per project may have is_current = TRUE.';

COMMENT ON COLUMN project_revisions.revision_number IS 'Sequential integer revision counter (1, 2, 3...). Unique per project.';
COMMENT ON COLUMN project_revisions.revision_code IS 'Human-readable revision code (A, B, C... or 1.0, 1.1...). Unique per project.';
COMMENT ON COLUMN project_revisions.project_snapshot IS 'JSONB snapshot of project metadata at time of this revision. Immutable after creation. Enables regulatory audit of historical project state.';
COMMENT ON COLUMN project_revisions.is_current IS 'TRUE for the most recent active revision. Enforced unique by partial index.';

-- Partial unique index: only one current revision per project
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_revisions_current
    ON project_revisions (project_id)
    WHERE is_current = TRUE;

-- ---------------------------------------------------------------------------
-- TABLE: project_notes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_notes (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id          UUID            NOT NULL,
    organization_id     UUID            NOT NULL,
    engineer_id         UUID            NOT NULL,
    note_type           VARCHAR(50)     NOT NULL DEFAULT 'comment',
    title               VARCHAR(255)    NOT NULL,
    content             TEXT            NOT NULL,
    is_system_generated BOOLEAN         NOT NULL DEFAULT FALSE,
    linked_entity_type  VARCHAR(100)    NULL,
    linked_entity_id    UUID            NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_project_notes
        PRIMARY KEY (id),

    CONSTRAINT fk_project_notes_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_notes_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_notes_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_notes_type
        CHECK (note_type IN (
            'decision','comment','status_change','rule_override',
            'milestone','warning','system','approval','rejection'
        )),

    CONSTRAINT chk_project_notes_content_not_blank
        CHECK (LENGTH(TRIM(content)) > 0),

    CONSTRAINT chk_project_notes_title_not_blank
        CHECK (LENGTH(TRIM(title)) > 0)
);

COMMENT ON TABLE project_notes IS
    'Append-only chronological audit log of events, decisions, and comments on a project. '
    'Records are NEVER updated or deleted — enforced by trigger and RLS. '
    'System-generated notes capture status changes, approvals, and overrides automatically. '
    'created_at is immutable: the note timestamp is the single source of truth.';

COMMENT ON COLUMN project_notes.created_at IS 'Immutable creation timestamp. Never modified after insert. The authoritative event timestamp.';
COMMENT ON COLUMN project_notes.is_system_generated IS 'TRUE when created automatically by the system (e.g., status change, rule override approval). FALSE for engineer-authored notes.';
COMMENT ON COLUMN project_notes.linked_entity_type IS 'Optional: PostgreSQL table name of a related entity this note references (e.g., stencil_designs, aperture_designs).';
COMMENT ON COLUMN project_notes.linked_entity_id IS 'Optional: UUID primary key of the linked entity record.';
COMMENT ON COLUMN project_notes.note_type IS
    'Classification: decision (engineering choice recorded), comment (general remark), '
    'status_change (project status transition), rule_override (override event), '
    'milestone (significant project event), warning (process risk flagged), '
    'system (automated system event), approval (revision approved), rejection (revision rejected).';

-- ---------------------------------------------------------------------------
-- TABLE: project_attachments
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_attachments (
    id                          UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id                  UUID            NOT NULL,
    organization_id             UUID            NOT NULL,
    uploaded_by_engineer_id     UUID            NOT NULL,
    filename                    VARCHAR(255)    NOT NULL,
    document_type               VARCHAR(50)     NOT NULL DEFAULT 'other',
    storage_path                TEXT            NOT NULL,
    storage_bucket              VARCHAR(100)    NOT NULL DEFAULT 'stencilpro-documents',
    file_size_bytes             BIGINT          NOT NULL,
    mime_type                   VARCHAR(100)    NOT NULL,
    description                 TEXT            NULL,
    version_label               VARCHAR(30)     NULL,
    is_deleted                  BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at                  TIMESTAMPTZ     NULL,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  UUID            NULL,
    updated_by                  UUID            NULL,

    CONSTRAINT pk_project_attachments
        PRIMARY KEY (id),

    CONSTRAINT fk_project_attachments_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_attachments_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_attachments_uploaded_by
        FOREIGN KEY (uploaded_by_engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_attachments_document_type
        CHECK (document_type IN (
            'datasheet','test_report','customer_spec','cad_file',
            'bom','gerber','odb_plus_plus','photo','procedure',
            'standard','contract','other'
        )),

    CONSTRAINT chk_project_attachments_file_size
        CHECK (file_size_bytes > 0),

    CONSTRAINT chk_project_attachments_storage_path_not_blank
        CHECK (LENGTH(TRIM(storage_path)) > 0),

    CONSTRAINT chk_project_attachments_soft_delete
        CHECK (
            (is_deleted = FALSE AND deleted_at IS NULL) OR
            (is_deleted = TRUE  AND deleted_at IS NOT NULL)
        )
);

COMMENT ON TABLE project_attachments IS
    'File attachments associated with a project. Binary data is stored in Supabase Storage; '
    'this table stores metadata and the storage path only. '
    'Soft-deleted attachments retain their metadata for audit trail purposes.';

COMMENT ON COLUMN project_attachments.storage_path IS 'Full path within Supabase Storage bucket (e.g., organizations/{org_id}/projects/{project_id}/attachments/{filename}).';
COMMENT ON COLUMN project_attachments.storage_bucket IS 'Supabase Storage bucket name. Defaults to stencilpro-documents.';
COMMENT ON COLUMN project_attachments.version_label IS 'Optional human version label for this attachment (e.g., Rev A, v2.1). Not enforced as unique.';
COMMENT ON COLUMN project_attachments.document_type IS 'Classification of the document to support filtering and display: datasheet, test_report, customer_spec, cad_file, bom, gerber, odb_plus_plus, photo, procedure, standard, contract, other.';

-- ---------------------------------------------------------------------------
-- TABLE: project_tags
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_tags (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID            NOT NULL,
    tag_name        VARCHAR(50)     NOT NULL,
    tag_color       VARCHAR(7)      NULL,
    tag_description TEXT            NULL,
    usage_count     INTEGER         NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_project_tags
        PRIMARY KEY (id),

    CONSTRAINT uq_project_tags_org_name
        UNIQUE (organization_id, tag_name),

    CONSTRAINT fk_project_tags_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_tags_name_format
        CHECK (tag_name ~ '^[a-z0-9_\-]{1,50}$'),

    CONSTRAINT chk_project_tags_color_format
        CHECK (tag_color IS NULL OR tag_color ~ '^#[0-9A-Fa-f]{6}$'),

    CONSTRAINT chk_project_tags_usage_count
        CHECK (usage_count >= 0)
);

COMMENT ON TABLE project_tags IS
    'Normalized tag definitions for projects. Enables organization-wide tag standardization '
    'and consistent search/filter. Tags are lowercase with hyphens (kebab-case). '
    'usage_count is maintained by trigger on project_tag_assignments.';

COMMENT ON COLUMN project_tags.tag_name IS 'Lowercase kebab-case tag (e.g., automotive, lead-free, high-reliability). Unique per organization.';
COMMENT ON COLUMN project_tags.tag_color IS 'Hex color code for UI display (e.g., #FF5733). NULL = use default theme color.';
COMMENT ON COLUMN project_tags.usage_count IS 'Count of active projects using this tag. Maintained by trigger. Used to identify and clean up unused tags.';

-- ---------------------------------------------------------------------------
-- TABLE: project_tag_assignments
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_tag_assignments (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    project_id      UUID            NOT NULL,
    tag_id          UUID            NOT NULL,
    organization_id UUID            NOT NULL,
    assigned_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    assigned_by     UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by      UUID            NULL,
    updated_by      UUID            NULL,

    CONSTRAINT pk_project_tag_assignments
        PRIMARY KEY (id),

    CONSTRAINT uq_project_tag_assignments_project_tag
        UNIQUE (project_id, tag_id),

    CONSTRAINT fk_project_tag_assignments_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_tag_assignments_tag
        FOREIGN KEY (tag_id)
        REFERENCES project_tags (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_tag_assignments_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_tag_assignments_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES engineers (id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE project_tag_assignments IS
    'Junction table assigning tags to projects. '
    'Cascade delete on project (if a project is hard-deleted, its tag assignments go too). '
    'Triggers update project_tags.usage_count on insert/delete.';

-- ---------------------------------------------------------------------------
-- TABLE: project_activity
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_activity (
    id              BIGSERIAL       NOT NULL,
    project_id      UUID            NOT NULL,
    organization_id UUID            NOT NULL,
    engineer_id     UUID            NULL,
    activity_type   VARCHAR(100)    NOT NULL,
    entity_type     VARCHAR(50)     NULL,
    entity_id       UUID            NULL,
    summary         VARCHAR(500)    NOT NULL,
    metadata        JSONB           NULL,
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_project_activity
        PRIMARY KEY (id),

    CONSTRAINT fk_project_activity_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_activity_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_project_activity_engineer
        FOREIGN KEY (engineer_id)
        REFERENCES engineers (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_activity_summary_not_blank
        CHECK (LENGTH(TRIM(summary)) > 0)
);

COMMENT ON TABLE project_activity IS
    'Append-only, high-resolution activity stream for a project. '
    'Records every significant action taken within a project context: '
    'stencil design created, analysis run, defect logged, report generated. '
    'Uses BIGSERIAL for strict ordering. Never modified after insert.';

COMMENT ON COLUMN project_activity.id IS 'BIGSERIAL sequence — guarantees strict chronological ordering within and across projects.';
COMMENT ON COLUMN project_activity.engineer_id IS 'NULL for system-generated activity (scheduled jobs, background processing).';
COMMENT ON COLUMN project_activity.activity_type IS 'Descriptor of the action (e.g., stencil_design.created, analysis.run, defect.logged, report.generated, member.added).';
COMMENT ON COLUMN project_activity.entity_type IS 'PostgreSQL table name of the primary entity involved (e.g., stencil_designs, aperture_designs).';
COMMENT ON COLUMN project_activity.summary IS 'Human-readable one-line description of the activity for the activity feed display.';
COMMENT ON COLUMN project_activity.metadata IS 'Structured context data specific to the activity type (e.g., {score_before: 68, score_after: 79} for analysis run).';

-- ---------------------------------------------------------------------------
-- TABLE: project_templates
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_templates (
    id                      UUID            NOT NULL DEFAULT gen_random_uuid(),
    organization_id         UUID            NULL,
    name                    VARCHAR(255)    NOT NULL,
    description             TEXT            NULL,
    default_phase           VARCHAR(30)     NOT NULL DEFAULT 'npi',
    default_ipc_class       VARCHAR(10)     NOT NULL DEFAULT 'class_2',
    default_tags            TEXT[]          NOT NULL DEFAULT '{}',
    template_settings       JSONB           NOT NULL DEFAULT '{}',
    is_system_template      BOOLEAN         NOT NULL DEFAULT FALSE,
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    usage_count             INTEGER         NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by              UUID            NULL,
    updated_by              UUID            NULL,

    CONSTRAINT pk_project_templates
        PRIMARY KEY (id),

    CONSTRAINT fk_project_templates_organization
        FOREIGN KEY (organization_id)
        REFERENCES organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_project_templates_default_phase
        CHECK (default_phase IN (
            'npi','pre_production','production',
            'eco','sustaining','end_of_life'
        )),

    CONSTRAINT chk_project_templates_default_ipc_class
        CHECK (default_ipc_class IN ('class_1','class_2','class_3')),

    CONSTRAINT chk_project_templates_usage_count
        CHECK (usage_count >= 0)
);

COMMENT ON TABLE project_templates IS
    'Reusable project configuration templates. '
    'organization_id = NULL means a system template available to all organizations. '
    'Templates pre-populate project metadata, default tags, phase, and IPC class '
    'to speed up common project types (NPI, ECO, Production Transfer). '
    'template_settings JSONB carries additional pre-configured values.';

COMMENT ON COLUMN project_templates.organization_id IS 'NULL = system template. Populated = custom template scoped to that organization.';
COMMENT ON COLUMN project_templates.template_settings IS 'JSONB bag of additional default values applied when a project is created from this template (e.g., default_stencil_material, default_paste_id, default_rule_set_id).';
COMMENT ON COLUMN project_templates.is_system_template IS 'TRUE = shipped with the application, read-only for all non-Super-Admin roles.';
COMMENT ON COLUMN project_templates.usage_count IS 'Count of projects created from this template. Maintained by trigger.';

COMMIT;
