-- =============================================================================
-- StencilPro Expert Enterprise
-- Module DB-004A: Engineering Knowledge Core
-- File: DB004A_Seed.sql
-- PostgreSQL 16 / Supabase Compatible
-- =============================================================================
-- Seed data for:
--   knowledge_sources          (6 sources)
--   engineering_rule_categories (22 categories)
--   engineering_rules          (12 example rules covering all source types)
--   engineering_rule_versions  (1 version per seeded rule)
--   engineering_rule_references (IPC references for system rules)
--   engineering_rule_actions   (default actions for seeded rules)
--   application_config         (rule engine settings)
-- =============================================================================
-- Fixed UUID strategy: 00000004A-{table_seq}-{record_seq}
-- =============================================================================

BEGIN;

-- =============================================================================
-- KNOWLEDGE SOURCES
-- =============================================================================

INSERT INTO knowledge_sources (
    id, code, name, description,
    base_priority, is_overridable,
    color_hex, icon_name, sort_order,
    is_active, is_system_record,
    created_at, updated_at
) VALUES

(
    '0000004a-0001-0001-0001-000000000001',
    'DEFAULT_RULE',
    'Default Rule',
    'Baseline default rules with no specific standard backing. '
    'Lowest priority — overridden by any other source. '
    'Represents conservative engineering defaults.',
    0, TRUE, '#9E9E9E', 'circle', 0,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0001-0001-0001-000000000002',
    'IPC_STANDARD',
    'IPC Standard',
    'Rules derived directly from IPC specifications including IPC-7525B, '
    'IPC-7093, IPC-7530, IPC-A-610, IPC-J-STD-004B, and related standards. '
    'These are the normative baseline for all SMT stencil engineering.',
    100, TRUE, '#1976D2', 'book', 1,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0001-0001-0001-000000000003',
    'AI_RECOMMENDATION',
    'AI Recommendation',
    'Rules and recommendations generated by the AI Recommendation Engine '
    'based on pattern recognition across historical designs, production outcomes, '
    'and the organization knowledge base. Confidence-weighted.',
    150, TRUE, '#7B1FA2', 'auto_fix_high', 2,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0001-0001-0001-000000000004',
    'COMPANY_RULE',
    'Company Rule',
    'Organization-specific engineering rules based on internal best practices, '
    'DOE results, and process knowledge. Supersedes IPC where more stringent.',
    200, TRUE, '#388E3C', 'business', 3,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0001-0001-0001-000000000005',
    'CUSTOMER_RULE',
    'Customer Rule',
    'Customer-specific requirements that supersede company and IPC rules. '
    'Derived from customer specifications, contractual requirements, '
    'and qualification standards.',
    300, TRUE, '#F57C00', 'person', 4,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0001-0001-0001-000000000006',
    'ENGINEER_OVERRIDE',
    'Engineer Override',
    'Explicit engineer judgment applied to a specific aperture or design context. '
    'Requires mandatory justification text. Critical overrides require Senior Engineer approval. '
    'Highest priority — overrides all other sources.',
    400, FALSE, '#D32F2F', 'engineering', 5,
    TRUE, TRUE, NOW(), NOW()
)

ON CONFLICT (code) DO NOTHING;

-- =============================================================================
-- ENGINEERING RULE CATEGORIES
-- =============================================================================

INSERT INTO engineering_rule_categories (
    id, parent_category_id, code, name, description,
    domain, applies_to, sort_order,
    is_active, is_system_record,
    created_at, updated_at
) VALUES

-- Top-level categories
(
    '0000004a-0002-0001-0001-000000000001',
    NULL, 'APERTURE_GEOMETRY', 'Aperture Geometry',
    'Rules governing the dimensional properties of stencil apertures.',
    'aperture', '{aperture_designs}', 10,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000002',
    NULL, 'PASTE_VOLUME', 'Paste Volume & Deposition',
    'Rules governing solder paste volume, transfer efficiency, and deposition quality.',
    'paste', '{aperture_designs,stencil_designs}', 20,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000003',
    NULL, 'MATERIAL_COMPATIBILITY', 'Material Compatibility',
    'Rules governing compatibility between stencil materials, coatings, and solder pastes.',
    'material', '{stencil_designs}', 30,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000004',
    NULL, 'THERMAL_PAD', 'Thermal Pad Design',
    'Rules governing paste aperture design for exposed thermal pads (QFN, LLP, DFN).',
    'thermal', '{aperture_designs}', 40,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000005',
    NULL, 'FINE_PITCH', 'Fine Pitch & Ultra Fine Pitch',
    'Rules for component pitches ≤0.5mm including ultra-fine-pitch ≤0.4mm.',
    'aperture', '{aperture_designs,stencil_designs}', 50,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000006',
    NULL, 'BGA_LGA', 'BGA / LGA Design',
    'Rules specific to Ball Grid Array and Land Grid Array component aperture design.',
    'aperture', '{aperture_designs}', 60,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000007',
    NULL, 'STENCIL_SPECIFICATION', 'Stencil Specification',
    'Rules governing overall stencil design parameters: material, thickness, coating.',
    'stencil', '{stencil_designs}', 70,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000008',
    NULL, 'PROCESS_ENVIRONMENT', 'Process Environment',
    'Rules governing print environment conditions: humidity, temperature, board support.',
    'process', '{stencil_designs}', 80,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000009',
    NULL, 'INSPECTION_REQUIREMENTS', 'Inspection Requirements',
    'Rules governing SPI, AOI, and X-ray inspection requirements per IPC class.',
    'inspection', '{stencil_designs}', 90,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000010',
    NULL, 'MIXED_TECHNOLOGY', 'Mixed Technology',
    'Rules for boards containing both SMT and through-hole components, '
    'or step stencil requirements.',
    'stencil', '{stencil_designs}', 100,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000011',
    NULL, 'REFLOW_PROCESS', 'Reflow Process',
    'Rules governing reflow profile parameters per IPC-7530.',
    'reflow', '{stencil_designs}', 110,
    TRUE, TRUE, NOW(), NOW()
),

-- Sub-categories of APERTURE_GEOMETRY
(
    '0000004a-0002-0001-0001-000000000012',
    '0000004a-0002-0001-0001-000000000001',
    'AREA_RATIO', 'Area Ratio',
    'Rules evaluating the IPC-7525B area ratio (aperture area / wall area).',
    'aperture', '{aperture_designs}', 11,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000013',
    '0000004a-0002-0001-0001-000000000001',
    'ASPECT_RATIO', 'Aspect Ratio',
    'Rules evaluating aperture aspect ratio (width / stencil thickness).',
    'aperture', '{aperture_designs}', 12,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000014',
    '0000004a-0002-0001-0001-000000000001',
    'APERTURE_SPACING', 'Aperture Spacing',
    'Rules governing minimum aperture-to-aperture and aperture-to-board-edge gaps.',
    'aperture', '{aperture_designs}', 13,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000015',
    '0000004a-0002-0001-0001-000000000001',
    'APERTURE_SHAPE', 'Aperture Shape',
    'Rules governing aperture shape selection and shape-specific geometry constraints.',
    'aperture', '{aperture_designs}', 14,
    TRUE, TRUE, NOW(), NOW()
),

-- Sub-categories of THERMAL_PAD
(
    '0000004a-0002-0001-0001-000000000016',
    '0000004a-0002-0001-0001-000000000004',
    'THERMAL_COVERAGE', 'Thermal Pad Coverage',
    'Rules governing paste coverage percentage on thermal pads per IPC-7093.',
    'thermal', '{aperture_designs}', 41,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000017',
    '0000004a-0002-0001-0001-000000000004',
    'THERMAL_SEGMENTATION', 'Thermal Pad Segmentation',
    'Rules governing aperture segmentation strategy for voiding control.',
    'thermal', '{aperture_designs}', 42,
    TRUE, TRUE, NOW(), NOW()
),

-- Sub-categories of STENCIL_SPECIFICATION
(
    '0000004a-0002-0001-0001-000000000018',
    '0000004a-0002-0001-0001-000000000007',
    'STENCIL_THICKNESS', 'Stencil Thickness',
    'Rules governing stencil thickness selection based on minimum pitch and component mix.',
    'stencil', '{stencil_designs}', 71,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000019',
    '0000004a-0002-0001-0001-000000000007',
    'STENCIL_MATERIAL', 'Stencil Material',
    'Rules governing stencil material selection (stainless, electroform, nickel).',
    'stencil', '{stencil_designs}', 72,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000020',
    '0000004a-0002-0001-0001-000000000007',
    'STENCIL_COATING', 'Stencil Coating',
    'Rules governing nano-coating and other release-enhancement coatings.',
    'stencil', '{stencil_designs}', 73,
    TRUE, TRUE, NOW(), NOW()
),

-- Sub-categories of PASTE_VOLUME
(
    '0000004a-0002-0001-0001-000000000021',
    '0000004a-0002-0001-0001-000000000002',
    'TRANSFER_EFFICIENCY', 'Transfer Efficiency',
    'Rules evaluating predicted paste transfer efficiency from aperture geometry.',
    'paste', '{aperture_designs}', 21,
    TRUE, TRUE, NOW(), NOW()
),
(
    '0000004a-0002-0001-0001-000000000022',
    '0000004a-0002-0001-0001-000000000002',
    'PASTE_COMPATIBILITY', 'Paste Compatibility',
    'Rules governing solder paste selection relative to stencil material and surface finish.',
    'paste', '{stencil_designs}', 22,
    TRUE, TRUE, NOW(), NOW()
)

ON CONFLICT (code) DO NOTHING;

-- =============================================================================
-- ENGINEERING RULES — System IPC Rules
-- =============================================================================

INSERT INTO engineering_rules (
    id, organization_id, knowledge_source_id, category_id,
    rule_code, name, description, rule_type, severity,
    ipc_class_scope, parameter_name, condition_operator,
    threshold_value, threshold_min, threshold_max, threshold_unit,
    base_confidence_pct, confidence_basis,
    message_pass, message_fail, message_warning,
    engineering_rationale, consequence_of_violation,
    expected_improvement_if_fixed, ipc_reference,
    related_defect_type_codes,
    is_overridable, override_requires_approval,
    override_justification_prompt,
    priority_score, is_active, is_deleted,
    created_by_source,
    created_at, updated_at
) VALUES

-- RULE 1: Area Ratio Minimum (IPC-7525B) — Critical
(
    '0000004a-0003-0001-0001-000000000001',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000012', -- AREA_RATIO
    'IPC7525B-001',
    'Minimum Area Ratio — Stainless Steel Stencil',
    'Evaluates the aperture area ratio (aperture opening area divided by aperture wall area) '
    'against the IPC-7525B minimum of 0.66 for stainless steel stencils.',
    'threshold', 'critical', 'all',
    'area_ratio', 'gte',
    0.660000, NULL, NULL, 'ratio',
    0.9500, 'well_established',
    'Area ratio {area_ratio:.3f} meets IPC-7525B minimum of 0.66.',
    'Area ratio {area_ratio:.3f} is BELOW the IPC-7525B minimum of 0.66. '
    'Paste release will be unreliable, causing insufficient solder volume.',
    'Area ratio {area_ratio:.3f} is marginal (0.66–0.72). '
    'Consider reducing stencil thickness or enlarging aperture.',
    'Area ratio is the single most predictive metric for paste release reliability. '
    'At area ratio < 0.66, adhesion forces between paste and aperture walls exceed '
    'the gravitational/surface-tension forces driving paste onto the pad. '
    'Transfer efficiency drops non-linearly below this threshold, '
    'typically from >80% to <50% at AR=0.55.',
    'Insufficient solder volume leading to opens, cold joints, and reduced '
    'interconnect reliability. In IPC Class 3 assemblies, this directly '
    'violates acceptance criteria.',
    'Increasing area ratio to ≥0.80 typically improves transfer efficiency from '
    '50% to 85%+, reducing insufficient solder defects by 60–80%.',
    'IPC-7525B Section 4.2',
    ARRAY['DEF-003','DEF-038','DEF-040'],
    TRUE, TRUE,
    'Provide engineering justification for accepting area ratio below 0.66. '
    'Include: actual measured transfer efficiency data, paste volume adequacy calculation, '
    'and risk mitigation plan.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 2: Aspect Ratio Minimum (IPC-7525B)
(
    '0000004a-0003-0001-0001-000000000002',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000013', -- ASPECT_RATIO
    'IPC7525B-002',
    'Minimum Aspect Ratio',
    'Evaluates aperture aspect ratio (aperture width / stencil thickness) '
    'against the IPC-7525B minimum of 1.5.',
    'threshold', 'major', 'all',
    'aspect_ratio', 'gte',
    1.500000, NULL, NULL, 'ratio',
    0.9200, 'well_established',
    'Aspect ratio {aspect_ratio:.2f} meets IPC-7525B minimum of 1.5.',
    'Aspect ratio {aspect_ratio:.2f} is BELOW the IPC-7525B minimum of 1.5. '
    'Stencil aperture walls may prevent paste release.',
    'Aspect ratio {aspect_ratio:.2f} is marginal (1.5–1.8).',
    'Aspect ratio (width/thickness) must be ≥1.5 to ensure the stencil aperture '
    'is wide enough relative to its depth for paste to release cleanly. '
    'Below 1.5, the stencil wall area begins to dominate, causing paste to stick '
    'in the aperture rather than depositing on the pad.',
    'Inconsistent paste deposition, aperture clogging over repeated print cycles, '
    'and reduced printing process capability.',
    'Increasing aspect ratio to ≥2.0 improves print repeatability significantly.',
    'IPC-7525B Section 4.2',
    ARRAY['DEF-003','DEF-012'],
    TRUE, TRUE,
    'Provide justification for aspect ratio below 1.5, including measured print data.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 3: Aperture-to-Aperture Gap
(
    '0000004a-0003-0001-0001-000000000003',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000014', -- APERTURE_SPACING
    'IPC7525B-003',
    'Minimum Aperture-to-Aperture Gap',
    'Evaluates the minimum gap between adjacent apertures. '
    'Minimum 0.15mm required; 0.20mm recommended for robust printing.',
    'threshold', 'major', 'all',
    'aperture_to_aperture_gap_mm', 'gte',
    0.150000, NULL, NULL, 'mm',
    0.8800, 'well_established',
    'Aperture gap {gap_mm:.3f}mm meets minimum spacing requirement.',
    'Aperture gap {gap_mm:.3f}mm is BELOW the 0.15mm minimum. '
    'Solder bridging between adjacent pads is likely.',
    'Aperture gap {gap_mm:.3f}mm is below the recommended 0.20mm. '
    'Bridge risk is elevated — consider aperture size reduction.',
    'Insufficient aperture-to-aperture spacing leaves inadequate stencil web '
    'between openings, causing the stencil to flex during squeegee traverse, '
    'solder paste to smear between apertures, and bridging defects after reflow.',
    'Solder bridges between adjacent pads, particularly on fine-pitch components. '
    'In BGAs, bridging can be invisible until X-ray inspection.',
    'Increasing gap to ≥0.20mm reduces bridge risk by approximately 65% '
    'in statistically controlled production environments.',
    'IPC-7525B Section 4.4',
    ARRAY['DEF-011'],
    TRUE, FALSE,
    'Provide bridging risk analysis and SPI data demonstrating bridge-free printing.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 4: Thermal Pad Coverage Maximum (IPC-7093)
(
    '0000004a-0003-0001-0001-000000000004',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000016', -- THERMAL_COVERAGE
    'IPC7093-001',
    'Thermal Pad Maximum Paste Coverage',
    'Evaluates thermal pad paste coverage percentage against IPC-7093 maximum. '
    'Coverage must not exceed 80% to prevent component float.',
    'threshold', 'critical', 'all',
    'thermal_pad_coverage_pct', 'lte',
    80.000000, NULL, NULL, '%',
    0.9000, 'well_established',
    'Thermal pad coverage {coverage_pct:.1f}% is within IPC-7093 limit of 80%.',
    'Thermal pad coverage {coverage_pct:.1f}% EXCEEDS the IPC-7093 maximum of 80%. '
    'Component floating and misalignment risk is HIGH.',
    NULL,
    'IPC-7093 limits thermal pad paste coverage to 80% maximum to prevent '
    'excess solder lifting the component body off adjacent signal pads during reflow. '
    'Excess paste under the thermal pad creates a hydraulic lifting force as the '
    'solder melts, causing component float and self-misalignment.',
    'Component body lifts off the PCB during reflow. Adjacent signal pad solder joints '
    'become open circuits. Component tilting causes catastrophic failure.',
    'Reducing coverage to 65–70% eliminates float risk while maintaining '
    'thermal performance above the minimum threshold.',
    'IPC-7093 Section 5.3',
    ARRAY['DEF-028'],
    TRUE, TRUE,
    'Provide thermal resistance calculation demonstrating adequate heat dissipation '
    'at the proposed coverage level.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 5: Thermal Pad Minimum Paste Coverage (IPC-7093)
(
    '0000004a-0003-0001-0001-000000000005',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000016', -- THERMAL_COVERAGE
    'IPC7093-002',
    'Thermal Pad Minimum Paste Coverage',
    'Evaluates thermal pad paste coverage percentage against IPC-7093 minimum. '
    'Coverage must be at least 50% for adequate thermal performance.',
    'threshold', 'major', 'all',
    'thermal_pad_coverage_pct', 'gte',
    50.000000, NULL, NULL, '%',
    0.8800, 'well_established',
    'Thermal pad coverage {coverage_pct:.1f}% meets IPC-7093 minimum of 50%.',
    'Thermal pad coverage {coverage_pct:.1f}% is BELOW the IPC-7093 minimum of 50%. '
    'Thermal performance will be inadequate and junction temperatures may exceed device limits.',
    'Thermal pad coverage {coverage_pct:.1f}% is between 50–60%. '
    'Consider increasing coverage toward the 65% recommended optimum.',
    'IPC-7093 requires minimum 50% thermal pad paste coverage to ensure '
    'sufficient solder joint contact area for heat dissipation. '
    'Below 50%, thermal resistance Rth increases rapidly, risking thermal shutdown '
    'or long-term junction degradation in power-dissipating components.',
    'Insufficient thermal solder joint area causes excessive device junction temperature. '
    'Long-term reliability degradation and potential thermal shutdown.',
    'Increasing coverage to 65% reduces thermal resistance by approximately 30%, '
    'significantly extending device lifetime.',
    'IPC-7093 Section 5.3',
    ARRAY['DEF-003'],
    TRUE, FALSE,
    'Provide thermal simulation data demonstrating junction temperature compliance '
    'at the proposed reduced coverage level.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 6: Reflow TAL Minimum (IPC-7530)
(
    '0000004a-0003-0001-0001-000000000006',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000011', -- REFLOW_PROCESS
    'IPC7530-001',
    'Minimum Time Above Liquidus',
    'Evaluates reflow profile time above liquidus (TAL) against '
    'IPC-7530 minimum of 30 seconds.',
    'threshold', 'critical', 'all',
    'reflow_tal_seconds', 'gte',
    30.000000, NULL, NULL, 's',
    0.9500, 'well_established',
    'Time above liquidus {tal_s:.0f}s meets IPC-7530 minimum of 30 seconds.',
    'Time above liquidus {tal_s:.0f}s is BELOW the IPC-7530 minimum of 30 seconds. '
    'Cold joint formation is likely.',
    NULL,
    'IPC-7530 requires minimum 30 seconds above liquidus to allow complete solder '
    'wetting, flux activation, and IMC layer formation. '
    'Below 30 seconds, incomplete wetting and cold (non-wetted) joints form, '
    'particularly on thermally massive components and inner-layer connections.',
    'Cold solder joints with high resistance, intermittent electrical failure '
    'under vibration or thermal cycling, and premature joint fatigue.',
    'Increasing TAL to 45–60 seconds ensures complete wetting '
    'and reliable IMC formation.',
    'IPC-7530 Section 4.1',
    ARRAY['DEF-035'],
    TRUE, TRUE,
    'Provide thermocouple data demonstrating adequate wetting and joint quality '
    'at the proposed TAL.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 7: Reflow TAL Maximum (IPC-7530)
(
    '0000004a-0003-0001-0001-000000000007',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000011', -- REFLOW_PROCESS
    'IPC7530-002',
    'Maximum Time Above Liquidus',
    'Evaluates reflow profile time above liquidus against '
    'IPC-7530 maximum of 90 seconds.',
    'threshold', 'major', 'all',
    'reflow_tal_seconds', 'lte',
    90.000000, NULL, NULL, 's',
    0.9200, 'well_established',
    'Time above liquidus {tal_s:.0f}s is within IPC-7530 maximum of 90 seconds.',
    'Time above liquidus {tal_s:.0f}s EXCEEDS the IPC-7530 maximum of 90 seconds. '
    'Excessive IMC growth and component damage risk.',
    'Time above liquidus {tal_s:.0f}s is between 75–90 seconds. '
    'Monitor for discoloration and component stress.',
    'IPC-7530 limits TAL to 90 seconds to control intermetallic compound (IMC) '
    'layer thickness. Excessive IMC growth makes the joint brittle. '
    'High TAL also increases thermal stress on ceramic capacitors, '
    'BGAs, and moisture-sensitive components.',
    'Brittle solder joints prone to cracking under mechanical shock. '
    'Component damage for MSL-sensitive parts. '
    'Ceramic capacitor cracking.',
    'Reducing TAL to 45–60 seconds minimizes IMC growth '
    'while maintaining complete wetting.',
    'IPC-7530 Section 4.1',
    ARRAY['DEF-035'],
    TRUE, FALSE,
    'Provide metallographic cross-section data showing IMC thickness '
    'is within acceptable limits.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 8: Nano Coating Recommendation for Fine Pitch (AI Recommendation)
(
    '0000004a-0003-0001-0001-000000000008',
    NULL,
    '0000004a-0001-0001-0001-000000000003', -- AI_RECOMMENDATION
    '0000004a-0002-0001-0001-000000000020', -- STENCIL_COATING
    'AI-COAT-001',
    'Nano Coating Recommended for Fine Pitch',
    'AI recommendation: for designs with minimum pitch ≤0.5mm, '
    'nano-coating the stencil improves transfer efficiency by 8–12%.',
    'advisory', 'advisory', 'all',
    'min_pitch_mm', 'lte',
    0.500000, NULL, NULL, 'mm',
    0.7800, 'probable',
    'Nano coating is applied — optimal for {min_pitch_mm}mm pitch.',
    NULL,
    'Design has {min_pitch_mm}mm minimum pitch without nano coating. '
    'AI recommends applying nano coating for improved paste release.',
    'Nano-coated stencil aperture walls have lower surface energy than bare stainless, '
    'reducing paste adhesion and improving transfer efficiency by 8–12% at fine pitch. '
    'The improvement is statistically significant for pitches ≤0.5mm where '
    'area ratio is challenging.',
    'Suboptimal transfer efficiency and higher paste volume variation '
    'on fine-pitch components.',
    'Adding nano coating at 0.5mm pitch typically improves transfer efficiency '
    'from 78% to 87% based on historical production data.',
    NULL,
    ARRAY['DEF-003','DEF-012'],
    TRUE, FALSE,
    NULL,
    150, TRUE, FALSE, 'ai',
    NOW(), NOW()
),

-- RULE 9: Area Ratio for Electroform Stencil (IPC-7525B variant)
(
    '0000004a-0003-0001-0001-000000000009',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000012', -- AREA_RATIO
    'IPC7525B-004',
    'Minimum Area Ratio — Electroform Stencil',
    'Evaluates the area ratio against the reduced IPC-7525B minimum of 0.60 '
    'permitted for electroform stencils due to their superior wall finish.',
    'threshold', 'critical', 'all',
    'area_ratio', 'gte',
    0.600000, NULL, NULL, 'ratio',
    0.9000, 'well_established',
    'Area ratio {area_ratio:.3f} meets electroform stencil minimum of 0.60.',
    'Area ratio {area_ratio:.3f} is BELOW the 0.60 minimum even for electroform stencils.',
    'Area ratio {area_ratio:.3f} is marginal for an electroform stencil (0.60–0.66).',
    'Electroform stencils have polished, tapered aperture walls that reduce '
    'paste adhesion compared to laser-cut stainless. '
    'IPC-7525B allows a reduced area ratio minimum of 0.60 for electroform stencils '
    'because the improved wall finish partially compensates for lower area ratio.',
    'Even with electroform construction, area ratio below 0.60 will result in '
    'unreliable paste release and variable solder volumes.',
    'Correcting aperture dimensions to achieve AR ≥0.66 (standard minimum) '
    'is the preferred solution. Electroform AR relief should be a last resort.',
    'IPC-7525B Section 4.2',
    ARRAY['DEF-003','DEF-038'],
    TRUE, TRUE,
    'Confirm stencil is electroform construction and provide process validation data.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 10: Paste Particle Size Rule of 5 (Company-type example)
(
    '0000004a-0003-0001-0001-000000000010',
    NULL,
    '0000004a-0001-0001-0001-000000000002', -- IPC_STANDARD
    '0000004a-0002-0001-0001-000000000022', -- PASTE_COMPATIBILITY
    'IPC7092-001',
    'Paste Particle Size Rule of Five',
    'Paste maximum particle diameter must not exceed 1/5 of the minimum aperture width. '
    'Ensures particle flow through the aperture without bridging or clogging.',
    'formula', 'major', 'all',
    'paste_max_particle_um', 'lte',
    NULL, NULL, NULL, 'µm',
    0.9300, 'well_established',
    'Paste particle size {particle_um:.0f}µm complies with Rule of 5 '
    '(max {max_allowed_um:.0f}µm for {min_aperture_width_mm:.3f}mm aperture).',
    'Paste particle size {particle_um:.0f}µm VIOLATES Rule of 5. '
    'Maximum allowed: {max_allowed_um:.0f}µm for {min_aperture_width_mm:.3f}mm aperture.',
    'Paste particle size is within Rule of 5 but close to the limit.',
    'The Rule of 5 states that the maximum solder particle diameter must be '
    '≤ 1/5 of the narrowest aperture opening. Larger particles cannot negotiate '
    'the aperture geometry and create blockages, causing insufficient paste deposits. '
    'For a 0.30mm aperture, maximum particle size = 60µm (T4 paste maximum).',
    'Aperture clogging, missing solder deposits, and print-to-print volume variation.',
    'Switching to a finer-powder paste (T5 for sub-0.25mm apertures) '
    'eliminates this risk entirely.',
    'IPC J-STD-005A',
    ARRAY['DEF-003','DEF-012'],
    TRUE, FALSE,
    'Provide print trial data demonstrating no aperture clogging over 500 prints.',
    100, TRUE, FALSE, 'system',
    NOW(), NOW()
),

-- RULE 11: Example Engineer Override Rule
(
    '0000004a-0003-0001-0001-000000000011',
    NULL,
    '0000004a-0001-0001-0001-000000000006', -- ENGINEER_OVERRIDE
    '0000004a-0002-0001-0001-000000000012', -- AREA_RATIO
    'ENG-OVERRIDE-EXAMPLE-001',
    'Engineer Override: Reduced Area Ratio (Example)',
    'Example engineer override rule demonstrating the override pattern. '
    'Not applied to any design by default.',
    'advisory', 'advisory', 'all',
    'area_ratio', 'gte',
    0.580000, NULL, NULL, 'ratio',
    0.6000, 'theoretical',
    'Engineer-overridden area ratio threshold met.',
    'Area ratio does not meet engineer override threshold.',
    NULL,
    'Engineer override accepting reduced area ratio based on process validation data. '
    'Requires documented justification and Senior Engineer approval.',
    'Potential for reduced transfer efficiency and paste volume variability.',
    'Accept only with validated production data demonstrating adequate joint quality.',
    NULL,
    ARRAY['DEF-003'],
    FALSE, TRUE,
    'This is an override of a critical IPC rule. Provide full process validation data.',
    400, FALSE, FALSE, 'engineer',
    NOW(), NOW()
),

-- RULE 12: Customer-Specific Tighter Area Ratio (Customer rule example)
(
    '0000004a-0003-0001-0001-000000000012',
    NULL,
    '0000004a-0001-0001-0001-000000000005', -- CUSTOMER_RULE
    '0000004a-0002-0001-0001-000000000012', -- AREA_RATIO
    'CUST-GENERIC-001',
    'Customer Standard: Minimum Area Ratio 0.70',
    'Example customer rule requiring a higher minimum area ratio of 0.70 '
    '(vs IPC minimum of 0.66). Demonstrates customer rule source type.',
    'threshold', 'major', 'all',
    'area_ratio', 'gte',
    0.700000, NULL, NULL, 'ratio',
    0.8500, 'customer_requirement',
    'Area ratio {area_ratio:.3f} meets customer minimum of 0.70.',
    'Area ratio {area_ratio:.3f} is BELOW customer minimum of 0.70. '
    'This customer requires a higher area ratio than the IPC minimum.',
    'Area ratio {area_ratio:.3f} is marginal against customer requirement (0.70–0.75).',
    'Some high-reliability customers impose tighter area ratio requirements '
    'than the IPC minimum to provide additional process margin for production variation. '
    'The 0.70 floor ensures transfer efficiency stays above 85% even with '
    'normal paste viscosity and environmental variation.',
    'Failure to meet customer specification. Possible customer audit findings '
    'and quality escape risk.',
    'Achieve AR ≥0.70 by adjusting aperture dimensions or reducing stencil thickness.',
    NULL,
    ARRAY['DEF-003','DEF-038'],
    TRUE, TRUE,
    'Provide customer-approved deviation request and yield data demonstrating compliance.',
    300, FALSE, FALSE, 'system',
    NOW(), NOW()
)

ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- ENGINEERING RULE VERSIONS
-- One initial version per seeded rule
-- =============================================================================

INSERT INTO engineering_rule_versions (
    id, rule_id, organization_id,
    version_number, version_label,
    change_summary, change_type,
    rule_snapshot,
    authored_by_engineer_id, approved_by_engineer_id,
    approved_at, effective_from, effective_until,
    is_current,
    created_at, updated_at
)
SELECT
    gen_random_uuid(),
    r.id,
    r.organization_id,
    1,
    '1.0',
    'Initial release — system seed.',
    'initial_release',
    to_jsonb(r),
    '00000001-0001-0001-0001-000000000005'::UUID,  -- super_admin role placeholder
    '00000001-0001-0001-0001-000000000005'::UUID,
    NOW(),
    NOW(),
    NULL,
    TRUE,
    NOW(),
    NOW()
FROM engineering_rules r
WHERE r.id LIKE '0000004a-0003%'
  AND NOT EXISTS (
    SELECT 1 FROM engineering_rule_versions rv
    WHERE rv.rule_id = r.id
  )
ON CONFLICT (rule_id, version_number) DO NOTHING;

-- =============================================================================
-- ENGINEERING RULE REFERENCES
-- =============================================================================

INSERT INTO engineering_rule_references (
    id, rule_id, reference_type,
    reference_code, reference_title,
    section_number, section_title,
    publication_year, url, summary,
    is_normative,
    created_at, updated_at
) VALUES

(
    '0000004a-0004-0001-0001-000000000001',
    '0000004a-0003-0001-0001-000000000001',
    'ipc_standard',
    'IPC-7525B',
    'Stencil Design Guidelines',
    '4.2', 'Area Ratio',
    2011, 'https://www.ipc.org/TOC/IPC-7525B.pdf',
    'Defines the area ratio formula and minimum threshold of 0.66 for stainless steel stencils.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000002',
    '0000004a-0003-0001-0001-000000000002',
    'ipc_standard',
    'IPC-7525B',
    'Stencil Design Guidelines',
    '4.2', 'Aspect Ratio',
    2011, 'https://www.ipc.org/TOC/IPC-7525B.pdf',
    'Defines the aspect ratio formula and minimum threshold of 1.5.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000003',
    '0000004a-0003-0001-0001-000000000003',
    'ipc_standard',
    'IPC-7525B',
    'Stencil Design Guidelines',
    '4.4', 'Aperture Spacing',
    2011, 'https://www.ipc.org/TOC/IPC-7525B.pdf',
    'Governs minimum aperture-to-aperture and aperture-to-board-edge spacing.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000004',
    '0000004a-0003-0001-0001-000000000004',
    'ipc_standard',
    'IPC-7093',
    'Design and Assembly Process Guidelines for Bottom Termination Components',
    '5.3', 'Solder Paste Coverage',
    2013, 'https://www.ipc.org/TOC/IPC-7093.pdf',
    'Defines 50–80% paste coverage range for exposed thermal pad apertures.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000005',
    '0000004a-0003-0001-0001-000000000005',
    'ipc_standard',
    'IPC-7093',
    'Design and Assembly Process Guidelines for Bottom Termination Components',
    '5.3', 'Solder Paste Coverage',
    2013, 'https://www.ipc.org/TOC/IPC-7093.pdf',
    'Defines 50% minimum paste coverage for thermal performance.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000006',
    '0000004a-0003-0001-0001-000000000006',
    'ipc_standard',
    'IPC-7530',
    'Guidelines for Temperature Profiling for Mass Soldering',
    '4.1', 'Time Above Liquidus',
    2017, 'https://www.ipc.org/TOC/IPC-7530.pdf',
    'Defines 30–90 second TAL window for SAC305 and similar alloys.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000007',
    '0000004a-0003-0001-0001-000000000007',
    'ipc_standard',
    'IPC-7530',
    'Guidelines for Temperature Profiling for Mass Soldering',
    '4.1', 'Time Above Liquidus',
    2017, 'https://www.ipc.org/TOC/IPC-7530.pdf',
    'Defines 90-second maximum TAL to control IMC growth.',
    TRUE,
    NOW(), NOW()
),
(
    '0000004a-0004-0001-0001-000000000008',
    '0000004a-0003-0001-0001-000000000010',
    'ipc_standard',
    'IPC J-STD-005A',
    'Requirements for Soldering Pastes',
    '3.2', 'Particle Size Classification',
    2012, NULL,
    'Defines solder paste powder size classifications T1 through T8 '
    'and application guidelines for aperture sizing.',
    TRUE,
    NOW(), NOW()
)

ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- ENGINEERING RULE ACTIONS — Default actions for critical rules
-- =============================================================================

INSERT INTO engineering_rule_actions (
    id, rule_id, organization_id,
    action_type, trigger_on,
    action_payload, recommendation_template,
    notification_type,
    blocks_approval, requires_override,
    sort_order, is_active,
    created_at, updated_at
) VALUES

-- Area ratio fail → flag + block approval
(
    '0000004a-0005-0001-0001-000000000001',
    '0000004a-0003-0001-0001-000000000001',
    NULL, 'flag_result', 'fail',
    '{"display_in_intelligence_panel": true, "highlight_aperture": true}'::JSONB,
    NULL, NULL,
    TRUE, TRUE,
    1, TRUE, NOW(), NOW()
),
(
    '0000004a-0005-0001-0001-000000000002',
    '0000004a-0003-0001-0001-000000000001',
    NULL, 'generate_recommendation', 'fail',
    '{"priority": "critical", "recommendation_type": "geometry_change"}'::JSONB,
    'Increase aperture dimensions to achieve area ratio ≥ 0.66. '
    'Current: {area_ratio:.3f}. '
    'Recommend: reduce stencil thickness from {thickness_mm}mm to {recommended_thickness_mm}mm, '
    'or increase aperture length from {length_mm:.3f}mm to {recommended_length_mm:.3f}mm.',
    'critical_rule_failure',
    FALSE, FALSE,
    2, TRUE, NOW(), NOW()
),

-- Aspect ratio fail → flag
(
    '0000004a-0005-0001-0001-000000000003',
    '0000004a-0003-0001-0001-000000000002',
    NULL, 'flag_result', 'fail',
    '{"display_in_intelligence_panel": true}'::JSONB,
    NULL, NULL,
    TRUE, TRUE,
    1, TRUE, NOW(), NOW()
),

-- Aperture gap fail → flag + recommendation
(
    '0000004a-0005-0001-0001-000000000004',
    '0000004a-0003-0001-0001-000000000003',
    NULL, 'flag_result', 'fail',
    '{"display_in_intelligence_panel": true, "highlight_aperture": true}'::JSONB,
    NULL, NULL,
    TRUE, FALSE,
    1, TRUE, NOW(), NOW()
),
(
    '0000004a-0005-0001-0001-000000000005',
    '0000004a-0003-0001-0001-000000000003',
    NULL, 'generate_recommendation', 'fail',
    '{"priority": "major", "recommendation_type": "geometry_change"}'::JSONB,
    'Reduce aperture size or adjust position to achieve minimum {min_gap_mm}mm gap. '
    'Current gap: {actual_gap_mm:.3f}mm.',
    NULL,
    FALSE, FALSE,
    2, TRUE, NOW(), NOW()
),

-- Thermal pad coverage max exceeded → critical block
(
    '0000004a-0005-0001-0001-000000000006',
    '0000004a-0003-0001-0001-000000000004',
    NULL, 'flag_result', 'fail',
    '{"display_in_intelligence_panel": true, "highlight_aperture": true}'::JSONB,
    NULL, NULL,
    TRUE, TRUE,
    1, TRUE, NOW(), NOW()
),

-- Reflow TAL minimum violated → critical
(
    '0000004a-0005-0001-0001-000000000007',
    '0000004a-0003-0001-0001-000000000006',
    NULL, 'flag_result', 'fail',
    '{"display_in_intelligence_panel": true}'::JSONB,
    NULL, 'critical_rule_failure',
    TRUE, TRUE,
    1, TRUE, NOW(), NOW()
),

-- AI nano coating recommendation → advisory action
(
    '0000004a-0005-0001-0001-000000000008',
    '0000004a-0003-0001-0001-000000000008',
    NULL, 'generate_recommendation', 'warning',
    '{"priority": "advisory", "recommendation_type": "process_enhancement"}'::JSONB,
    'Apply nano coating to stencil to improve transfer efficiency '
    'by an estimated 8–12% on {min_pitch_mm}mm pitch apertures.',
    NULL,
    FALSE, FALSE,
    1, TRUE, NOW(), NOW()
)

ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- APPLICATION CONFIG — Rule Engine settings
-- =============================================================================

INSERT INTO application_config (
    id, config_key, config_value, config_type, environment,
    description, created_at, updated_at
) VALUES

(
    '0000004a-0006-0001-0001-000000000001',
    'rule_engine.min_area_ratio_stainless',
    '0.66',
    'string', 'all',
    'IPC-7525B minimum area ratio for stainless steel stencils.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000002',
    'rule_engine.min_area_ratio_electroform',
    '0.60',
    'string', 'all',
    'IPC-7525B minimum area ratio for electroform stencils.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000003',
    'rule_engine.min_aspect_ratio',
    '1.5',
    'string', 'all',
    'IPC-7525B minimum aperture aspect ratio (width / stencil thickness).',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000004',
    'rule_engine.min_aperture_gap_mm',
    '0.15',
    'string', 'all',
    'Minimum aperture-to-aperture gap in mm.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000005',
    'rule_engine.recommended_aperture_gap_mm',
    '0.20',
    'string', 'all',
    'Recommended aperture-to-aperture gap in mm for robust printing.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000006',
    'rule_engine.thermal_pad_coverage_min_pct',
    '50.0',
    'string', 'all',
    'IPC-7093 minimum thermal pad paste coverage percentage.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000007',
    'rule_engine.thermal_pad_coverage_max_pct',
    '80.0',
    'string', 'all',
    'IPC-7093 maximum thermal pad paste coverage percentage.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000008',
    'rule_engine.thermal_pad_coverage_optimal_pct',
    '65.0',
    'string', 'all',
    'Optimal thermal pad paste coverage percentage (centre of IPC-7093 window).',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000009',
    'rule_engine.reflow_tal_min_seconds',
    '30',
    'integer', 'all',
    'IPC-7530 minimum time above liquidus in seconds.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000010',
    'rule_engine.reflow_tal_max_seconds',
    '90',
    'integer', 'all',
    'IPC-7530 maximum time above liquidus in seconds.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000011',
    'rule_engine.priority.project_override',
    '500',
    'integer', 'all',
    'Rule priority score for project-level overrides.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000012',
    'rule_engine.priority.engineer_override',
    '400',
    'integer', 'all',
    'Rule priority score for engineer-level overrides.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000013',
    'rule_engine.priority.customer_rule',
    '300',
    'integer', 'all',
    'Rule priority score for customer-specific rules.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000014',
    'rule_engine.priority.company_rule',
    '200',
    'integer', 'all',
    'Rule priority score for company/organization rules.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000015',
    'rule_engine.priority.ai_recommendation',
    '150',
    'integer', 'all',
    'Rule priority score for AI-generated recommendations.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000016',
    'rule_engine.priority.ipc_standard',
    '100',
    'integer', 'all',
    'Rule priority score for IPC standard rules.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000017',
    'rule_engine.priority.default_rule',
    '0',
    'integer', 'all',
    'Rule priority score for default/baseline rules.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000018',
    'rule_engine.confidence_clamp_min',
    '0.10',
    'string', 'all',
    'Minimum confidence score after learning updates (Learning Engine clamp floor).',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000019',
    'rule_engine.confidence_clamp_max',
    '0.99',
    'string', 'all',
    'Maximum confidence score after learning updates (Learning Engine clamp ceiling).',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000020',
    'rule_engine.learning_rate',
    '0.05',
    'string', 'all',
    'Learning rate applied to confidence updates: new = old + (delta * strength * rate).',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000021',
    'rule_engine.min_override_justification_chars',
    '50',
    'integer', 'all',
    'Minimum character count for engineering rule override justification text.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000022',
    'rule_engine.what_if_max_saved_per_engineer',
    '20',
    'integer', 'all',
    'Maximum number of saved what-if scenarios per engineer per organization.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000023',
    'rule_engine.what_if_result_retention_days',
    '365',
    'integer', 'all',
    'Number of days to retain unsaved what-if results before auto-archiving.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000024',
    'rule_engine.effectiveness_compute_period_months',
    '1',
    'integer', 'all',
    'Frequency in months of rule effectiveness history computation.',
    NOW(), NOW()
),
(
    '0000004a-0006-0001-0001-000000000025',
    'rule_engine.ai_min_confidence_display_pct',
    '0.75',
    'string', 'all',
    'Minimum AI confidence (0.0–1.0) before a recommendation is displayed in the UI.',
    NOW(), NOW()
)

ON CONFLICT (config_key, environment) DO NOTHING;

-- =============================================================================
-- MIGRATION RECORD
-- =============================================================================

INSERT INTO schema_migrations (version_num, applied_at)
VALUES ('0004A_db004a_engineering_knowledge_core', NOW())
ON CONFLICT (version_num) DO NOTHING;

COMMIT;
